services:
  fifa-mysql:
    image: mysql:8.0
    container_name: vote-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: fifa_mysql
      MYSQL_DATABASE: fifa_vote_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vote-backend
    restart: always
    ports:
      - "5139:8080"
    depends_on:
      fifa-mysql:
        condition: service_healthy
    environment:
      - ConnectionStrings__DefaultConnection=server=fifa-mysql;port=3306;database=fifa_vote_db;user=root;password=fifa_mysql
      - ASPNETCORE_ENVIRONMENT=Production

  frontend:
    build:
      context: ../fifa-frontend
      dockerfile: Dockerfile
    container_name: vote-frontend
    restart: always
    ports:
      - "4200:80"
    depends_on:
      - backend

volumes:
  mysql_data: